spring:
  application:
    name: dev-demo
  datasource:
    url: jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable
    username: root
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
